### ISSUE TITLE
Suggestion: ESbuild plugin

### ISSUE THREAD

**Issue by tomByrer** [js-choi/proposal-bind-operator#1]
babel is cool, but slow & I've seen many new projects skip Babel & use Vite or [ESBuild](https://esbuild.github.io/plugins/), both of which run much faster, saving both time & energy.

**Comment by js-choi** [comment]
Thanks for raising this issue.

To my knowledge, there is not a very big ES-proposal transpilation ecosystem with ESBuild, which has (reasonably) focused specifically on bundling and minification. So, if I actually did pursue this proposal (it’s still in flux), I would probably use Babel, like all other TC39 syntax proposals have done.

Hopefully that makes sense. :)
